### ISSUE TITLE
gradle.properties values with `:` in them break parsing

### ISSUE THREAD

**Issue by doorhinge** [KengoTODA/gradle-semantic-release-plugin#186]
This is probably more of an issue with the [promisified-properties library](https://github.com/KengoTODA/promisified-properties), but if a `gradle.properties` file has a value with a `:` character in it (such as a URL) it breaks the plugin.

For example, I updated the `test/project/with-properties-file/gradle.properties` file to look like this:

```
version = 0.1.2
some_url = https://lol.gov
```

and when running `npm run test` got the following error:

```
  1) Test for prepare step
       updateVersion() will update version in gradle.properties:
     Error:
-- PARSING FAILED --------------------------------------------------

> 1 | some_url = https://lol.gov
    |                 ^

Expected:

EOF
```

**Comment by KengoTODA** [comment]
@doorhinge Thanks for reporting this issue! Please try the version `1.4.1`, it should solve your problem.
