### ISSUE TITLE
The property(ies) to update in gradle.properties should be configurable.

### ISSUE THREAD

**Issue by goldy1992** [KengoTODA/gradle-semantic-release-plugin#346]
At the moment.... the must be a property `version` in the `gradle.properties` file in order for the plugin to work correctly. 

We should be able to configure the name of the property to set.
For example... consider an android project with multiple build variants. Each build variant should have it's own version property configured meaning different build variant releases would have a different version property. See https://developer.android.com/studio/publish/versioning

**Comment by goldy1992** [comment]
Actually now I come to think of it... maybe a better place to do the upping of versions would be a custom script using the [@semantic-release/exec](https://github.com/semantic-release/exec) plugin. 

What do you think @KengoTODA ?

**Comment by KengoTODA** [comment]
I also think so :) then I'll close this issue.
