### ISSUE TITLE
Unsupported engine during npm update

### ISSUE THREAD

**Issue by dotCipher** [KengoTODA/gradle-semantic-release-plugin#466]
When running `npm update` on a repo with this plugin it fails with the following error:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'gradle-semantic-release-plugin@1.6.7',
npm WARN EBADENGINE   required: { node: '^16.14.0' },
npm WARN EBADENGINE   current: { node: 'v17.6.0', npm: '8.5.1' }
npm WARN EBADENGINE }
```

Does this not work with node `v17.6.0` ?

**Comment by KengoTODA** [comment]
Just not sure, because I haven't tested this product with non-LTS version.
It probably works, but not been verified yet.
