### ISSUE TITLE
Release new version to support semantic-release v22

### ISSUE THREAD

**Issue by mirkolenz** [KengoTODA/gradle-semantic-release-plugin#554]
In #547 you updated semantic-release to v22. Since then, no new release has been published. I just encountered a conflict due to this: https://github.com/recap-utr/arg-services-java/actions/runs/6653570916/job/18079876725#step:5:119

For the meantime, I have downgraded to semantic-release v21, but would like to bump conventional-changelog-conventionalcommits to the latest version.

BTW: Thank you for maintaining this package, it makes my life a lot easier in Java projects!

**Comment by KengoTODA** [comment]
closed by #561, thanks for your report!

**Comment by mirkolenz** [comment]
Great, thank you!
