### ISSUE TITLE
Preserve comments in gradle.properties

### ISSUE THREAD

**Issue by jcapogna** [KengoTODA/gradle-semantic-release-plugin#569]
When saving the new version in gradle.properties, the file is rewritten and any comments are stripped out as a result. Is it possible to only update the version property and leave the rest of the file intact?

**Comment by KengoTODA** [comment]
This feature needs breaking changes in https://github.com/KengoTODA/promisified-properties repo, I'll track this request as https://github.com/KengoTODA/promisified-properties/issues/665

**Comment by jcapogna** [comment]
Thanks @KengoTODA 

This still removes blank lines, but it does preserve line order and comments. Saving blank lines would be a nice plus if possible.
